# Generated by Django 2.2 on 2021-10-20 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='Symptoms',
            new_name='symptoms',
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_address',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
