# Generated by Django 2.2 on 2021-10-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_auto_20211020_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prescription',
            new_name='Prescriptions',
        ),
    ]
