# Generated by Django 2.2 on 2021-10-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_auto_20211020_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.CharField(blank=True, default='00.00 AM/PM', max_length=20, null=True),
        ),
    ]
