# Generated by Django 2.2 on 2021-10-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0005_auto_20211020_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
