# Generated by Django 2.2 on 2021-11-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0006_auto_20211020_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date',
        ),
        migrations.AddField(
            model_name='appointments',
            name='dates',
            field=models.DateField(default=None, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.TimeField(default=None, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='symptoms',
            field=models.CharField(max_length=1000),
        ),
    ]
